---
- name: Sync requisition
  ansible.builtin.uri:
    url: "{{ horizon.resturl }}/{{ horizon.requisitionsapi }}/{{ requisition }}/import?rescanExisting=true"
    user: "{{ horizon.user }}"
    password: "{{ horizon.password }}"
    method: PUT
    status_code: 202
    headers:
      Content-Type: "application/xml"
