---
- name: Sync requisition
  ansible.builtin.uri:
    url: "{{ onms_hzn.base_rest_url }}/{{ onms_hzn.requisitions_api }}/{{ onms_requisition }}/import?rescanExisting=true"
    user: "{{ onms_hzn.user }}"
    password: "{{ onms_hzn.password }}"
    method: PUT
    status_code: 202
    headers:
      Content-Type: "application/xml"
