---
# Ansible node settings
ansible_connection: ssh
ansible_user: ubuntu
ansible_ssh_pass: ubuntu

# Horizon server settings
horizon:
  resturl: http://172.16.238.11:8980/opennms/rest
  nodeapi: nodes
  requisitionsapi: requisitions
  foreignSourcesapi: foreignSources
  interfacesapi: interfaces
  user: admin
  password: admin

# General node settings
snmpd_inform_sink: 172.16.238.10
requisition: stack1-{{ env }}
services:
  ICMP:
  SNMP:
  HTTP.MyApp:
    port: "{{ http_port }}"
    path: "/"
horizon_node_location: "Default"
