---
# Ansible node settings
ansible_connection: ssh
ansible_user: ubuntu
ansible_ssh_pass: ubuntu

# Monitoring configuration
snmpd_inform_sink: 172.16.238.10

# OpenNMS Horizon server settings
onms_hzn:
  base_rest_url: http://172.16.238.11:8980/opennms/rest
  node_api: nodes
  requisitions_api: requisitions
  foreign_sources_api: foreignSources
  interfaces_api: interfaces
  user: admin
  password: admin

onms_requisition: stack1-{{ env }}
onms_location: "Default"

onms_group_services:
   ICMP: {}
   SNMP: {}

onms_host_services: {}

# OpenNMS Horizon provision policies
policies:
  ignore_interfaces:
    class: org.opennms.netmgt.provision.persist.policies.MatchingSnmpInterfacePolicy
    parameters:
      action: DO_NOT_PERSIST
      ifDescr: "~^(docker|tap|veth).*$"
      matchBehavior: ALL_PARAMETERS
  set_metdadata_alerting_channel:
    class: org.opennms.netmgt.provision.persist.policies.NodeMetadataSettingPolicy
    parameters:
      foreignSource: "{{ onms_requisition }}"
      metadataKey: slackchannel
      metadataValue: "alerting-{{onms_requisition}}"
      matchBehavior: ANY_PARAMETER
  set_category_if_linux_os:
    class: org.opennms.netmgt.provision.persist.policies.NodeCategorySettingPolicy
    parameters:
      category: linux
      sysObjectId: |-
        ~^\.1\.3\.6\.1\.4\.1\.8072\.3\.2\.10.*
      matchBehavior: ALL_PARAMETERS
