---
horizon:
  resturl: http://172.16.238.11:8980/opennms/rest
  nodeapi: nodes
  requisitionsapi: requisitions
  foreignSourcesapi: foreignSources
  interfacesapi: interfaces
  user: admin
  password: admin
