---
# Ansible node settings
ansible_connection: ssh
ansible_user: ubuntu
ansible_ssh_pass: ubuntu

# OpenNMS Horizon server settings
# Customize to your needs
onms_hzn:
  base_rest_url: http://172.16.238.11:8980/opennms/rest
  user: admin
  password: admin
