---
- name: Install Apache 2
  apt: name=apache2 update_cache=yes state=latest

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: apache2 listen on port {{ port }}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen.*" line="Listen {{ port }}" state=present
  notify:
    - restart apache2

- name: apache2 virtualhost on port {{ port }} }}
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:.*>" line="<VirtualHost *:{{ port }}>" state=present
  notify:
    - restart apache2
