---
- name: "Install Apache 2"
  apt: name=apache2 update_cache=yes state=latest

- name: "Enabled mod_rewrite"
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: "Apache 2 listen on port {{ http_port }}"
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen.*" line="Listen {{ http_port }}" state=present
  notify:
    - restart apache2

- name: "Apache 2 virtualhost on port {{ http_port }}"
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:.*>" line="<VirtualHost *:{{ http_port }}>" state=present
  notify:
    - restart apache2
