---
ansible_host: 172.16.238.12
onms_location: "Default"
onms_host_services:
  HTTP.MyApp:
    port: "{{ http_port }}"
    path: "/"

onms_node_parent_foreign_id: "1000"

onms_host_metadata:
  department: "Finance"
