---
http_port: 81

snmpd_inform_sink: 172.16.238.11

onms_requisition_name: staging

# Node MetaData in key/value pairs
onms_group_metadata:
   env: staging

onms_host_categories:
   - staging

onms_group_services:
   ICMP: {}
