---
switches:
  hosts:
    switch1:
      ansible_host: 172.16.238.14
      onms_host_services:
        SNMP:
          retry: 30
          timeout: 6000
      onms_node_additional_nic:
        "172.16.238.20":
          ICMP:
            retry: 5
            timeout: 10
          HTTP:
            port: 90
        "172.16.238.21":
          SNMP:
            retry: 5
            timeout: 10
      onms_host_metadata:
        env: prod
      onms_host_categories:
        - prod
    switch2:
      ansible_host: 172.16.238.15
      onms_host_services:
        HTTP:
          retry: 13
          port: 8100
      onms_host_metadata:
        env: staging
      onms_host_categories:
        - staging
      onms_host_parentnodelabel: switch1
