---
- name: Install snmpd packages
  apt: name=snmpd state=present
  tags: ['net-snmp']

- name: Add the user 'snmp'
  ansible.builtin.user:
    name: snmp

- name: Ensures {{ snmpd_include_dir }} dir exists
  file: path={{ snmpd_include_dir }} state=directory mode=0640
  tags: ['net-snmp']

- name: Set snmpd default settings
  copy: src=files/etc/snmpd.default dest=/etc/default/snmpd owner=root group=root mode="0640"
  tags: ['net-snmp']

- name: Copy the snmpd.conf template file
  template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf
  mode: 0644
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Enable disk monitoring
  template: src=disk.conf.j2 dest={{ snmpd_include_dir }}/disk.conf
  mode: 0644
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Enable process monitoring
  template: src=proc.conf.j2 dest={{ snmpd_include_dir }}/proc.conf
  mode: 0644
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Copy the Trap Inform template file
  template: src=inform.conf.j2 dest={{ snmpd_include_dir }}/inform.conf
  mode: 0644
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Copy the sysinfo inform template file
  template: src=sysinfo.conf.j2 dest={{ snmpd_include_dir }}/sysinfo.conf
  mode: 0644
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: "Start service snmpd"
  ansible.builtin.service:
    name: snmpd
    state: started
