---
- name: Install snmpd packages
  ansible.builtin.apt:
    name: snmpd
    state: present
  tags: ['net-snmp']

- name: Add the user 'snmp'
  ansible.builtin.user:
    name: snmp

- name: Ensures include dir exists
  ansible.builtin.file:
    path: "{{ snmpd_include_dir }}"
    state: directory
    mode: "0640"
  tags: ['net-snmp']

- name: Set snmpd default settings
  ansible.builtin.copy:
    src: files/etc/snmpd.default
    dest: /etc/default/snmpd
    owner: root
    group: root
    mode: "0640"
  tags: ['net-snmp']

- name: Copy the snmpd.conf template file
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    mode: "0640"
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Enable disk monitoring
  ansible.builtin.template:
    src: disk.conf.j2
    dest: "{{ snmpd_include_dir }}/disk.conf"
    mode: "0640"
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Enable process monitoring
  ansible.builtin.template:
    src: proc.conf.j2
    dest: "{{ snmpd_include_dir }}/proc.conf"
    mode: "0640"
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Copy the Trap Inform template file
  ansible.builtin.template:
    src: inform.conf.j2
    dest: "{{ snmpd_include_dir }}/inform.conf"
    mode: "0640"
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: Copy the sysinfo inform template file
  ansible.builtin.template:
    src: sysinfo.conf.j2
    dest: "{{ snmpd_include_dir }}/sysinfo.conf"
    mode: "0640"
  notify:
    - restart snmpd
  tags: ['net-snmp']

- name: "Start service snmpd"
  ansible.builtin.service:
    name: snmpd
    state: started
