---
# A collection of tasks that can help developing the playbook

# Creates a file in the root folder and writes the node definition into it.
# This is helpful if you want to change the node_xml.j2 and see the exact output.
- name: Create node defintion xml file
  ansible.builtin.template:
    src: node_xml.j2
    dest: "node_definition_{{ ansible_host }}.xml"
    mode: '0644'
  delegate_to: localhost
