---
- name: Check if node is existent
  ansible.builtin.uri:
    url: "{{ horizon.resturl }}/{{ horizon.requisitionsapi }}/ansible-inventory/{{ horizon.nodeapi }}/{{ ansible_facts['machine_id'] }}"
    user: "{{ horizon.user }}"
    password: "{{ horizon.password }}"
    method: GET
    force_basic_auth: true
    status_code: 200
  ignore_errors: true
  no_log: true
  register: result
#- name: Print all available facts
#  ansible.builtin.debug:
#    var: ansible_facts
#  when: result.failed
- name: REST call Create Node
  ansible.builtin.uri:
    url: "{{ horizon.resturl }}/{{ horizon.requisitionsapi }}/ansible-inventory/nodes"
    user: "{{ horizon.user }}"
    password: "{{ horizon.password }}"
    method: POST  
    status_code: 202
    headers: 
      Content-Type: "application/xml" 
    body: "{{lookup('template','node_xml.j2')}}" 
  register: node_created
  when: result.failed
- name: synchronize_requisition
  ansible.builtin.uri:
    url: "{{ horizon.resturl }}/{{ horizon.requisitionsapi }}/ansible-inventory/import?rescanExisting=false"
    user: "{{ horizon.user }}"
    password: "{{ horizon.password }}"
    method: PUT
    status_code: 202
    headers: 
      Content-Type: "application/xml"
  when: node_created
