---
- name: "Deletes node in requisitions"
  ansible.builtin.uri:
    url: "{{ onms_hzn_base_rest_url }}/{{ onms_hzn_requisitions_api }}/{{ onms_requisition_name }}/nodes/{{ onms_host_foreignid }}"
    user: "{{ onms_hzn_user }}"
    password: "{{ onms_hzn_password }}"
    method: DELETE
    status_code: 202
  no_log: false
  register: node_deleted
  delegate_to: localhost

- name: "Import requisitions"
  ansible.builtin.uri:
    url: "{{ onms_hzn_base_rest_url }}/{{ onms_hzn_requisitions_api }}/{{ onms_requisition_name }}/import?rescanExisting=true"
    user: "{{ onms_hzn_user }}"
    password: "{{ onms_hzn_password }}"
    method: PUT
    status_code: 202
    headers:
      Content-Type: "application/xml"
  when:
    - node_deleted
  delegate_to: localhost
