---
# Configuration only used for the inventory `switches`
onms_requisition_name: switches
ansible_connection: local
onms_location: "Default"
onms_group_services:
   ICMP: {}
onms_host_services: {}
onms_policies: {}

# Node MetaData in key/value pairs
onms_host_metadata:
   env: prod
   app: switches
