---
env: production
http_port: 80

# OpenNMS Horizon provision policies
policies:
  # There are often special interfaces for that we don't want to collect data/monitor
  ignore_interfaces:
    class: org.opennms.netmgt.provision.persist.policies.MatchingSnmpInterfacePolicy
    parameters:
      action: DO_NOT_PERSIST
      ifDescr: "~^(docker|tap|veth).*$"
      matchBehavior: ALL_PARAMETERS
  # Based on the SysObjId for Linux net-nnmp agent, the category "linux" will be added
  set_category_if_linux_os:
    class: org.opennms.netmgt.provision.persist.policies.NodeCategorySettingPolicy
    parameters:
      category: linux
      sysObjectId: |-
        ~^\.1\.3\.6\.1\.4\.1\.8072\.3\.2\.10.*
      matchBehavior: ALL_PARAMETERS
  # All nodes in the requisition get a node MetaData that can be used to send notifications to a specific destinationPath
  set_metdadata_alerting_channel:
    class: org.opennms.netmgt.provision.persist.policies.NodeMetadataSettingPolicy
    parameters:
      foreignSource: "{{ onms_requisition }}"
      metadataKey: alerting_channel
      metadataValue: "alerting-{{onms_requisition}}"
      matchBehavior: ANY_PARAMETER
