---
# file: horizon-provision.yaml

- name: API Check
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Query ONMS info API
      uri:
        url: "{{ onms_hzn_base_rest_url }}/info"
        user: "{{ onms_hzn_user }}"
        password: "{{ onms_hzn_password }}"
        method: GET
        force_basic_auth: true
        validate_certs: false
        status_code: 200
      register: info_output
    - name: Fetch ONMS version
      set_fact:
        onms_version: "{{ info_output | json_query(jmesquery) }}"
      vars:
        jmesquery: '*."version" | [0]'
    - name: Verify ONMS version
      assert:
        that:
          - "'{{ onms_version }}' is version ('{{ onms_api_version }}', '>=', version_type='semver')"
        fail_msg: "You need at least OpenNMS {{ onms_api_version }} or greater to run these tasks. Your OpenNMS version is {{ onms_version }}."
- name: Group of hosts provisioned into OpenNMS Horizon
  hosts: monitoring
  gather_facts: true
  become: true
  roles:
    - horizon-provision
  tasks:
    - name: "Import requisitions"
      ansible.builtin.uri:
        url: "{{ onms_hzn_base_rest_url }}/{{ onms_hzn_requisitions_api }}/{{ onms_requisition_name }}/import?rescanExisting=true"
        user: "{{ onms_hzn_user }}"
        password: "{{ onms_hzn_password }}"
        method: PUT
        status_code: 202
        headers:
          Content-Type: "application/xml"
