---
# Default settings to let this playbook work without touching the group vars
onms_hzn:
  base_rest_url: http://172.16.238.11:8980/opennms/rest
  node_api: nodes
  requisitions_api: requisitions
  foreign_sources_api: foreignSources
  interfaces_api: interfaces
  user: admin
  password: admin
